# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b293ecaa687874e641114a2ccfa247795996bf30d397b9b2acbe35b8421f5d52a9b5bf06573bd2a1a74dedebe9bb411070a37cba99d4967c1153467aa6dca2f

test:
  secret_key_base: c58c36ac90812c87a8d78bc188ad7835ee36e6f421d71412edec8aa1b4e5e74b7f1e81fde1c0faff3c310f98185e6f8d02063d0daffa482d4ae9d905f7d43ec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
